title: Md Habibur Rahman Sifat
logo: /img/sifat_circle_image.png
description: Researcher in Machine Learning and Computational Biology
# show_downloads: true
# theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# Optional settings
url: "https://habibsifat.github.io"
baseurl: ""

social_links:
  - name: LinkedIn
    url: https://www.linkedin.com/in/habibsifat/
    icon: linkedin
  # - name: Facebook
  #   url: https://facebook.com/your-profile
  #   icon: facebook
